package by.it_academy.controller;

public enum CommandName {
	GO_TO_AUTHENTICATION,
	GO_TO_REGISTRATION,
	DO_AUTHENTICATION,
	DO_REGISTRATION,
	GO_TO_BASE_PAGE,
	DO_SINGOUT,
	GO_TO_VIEW_NEWS,
	GO_TO_ADD_NEWS,
	DO_ADD_NEWS,
	GO_TO_LOCAL,
	GO_TO_EDIT_NEWS,
	DO_EDIT_NEWS;

}
